# Generated by Django 5.0.3 on 2024-04-22 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0003_rename_users_myusers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUsers',
            new_name='Students',
        ),
    ]
