# Generated by Django 5.0.6 on 2024-05-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='strategy',
            new_name='script',
        ),
    ]
