# Generated by Django 5.0.6 on 2024-05-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0008_rename_strategy_strategy_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='script',
        ),
        migrations.AddField(
            model_name='strategy',
            name='rendered',
            field=models.TextField(blank=True, default='', verbose_name='Rendered strategy'),
        ),
    ]
