# Generated by Django 5.0.6 on 2024-05-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0009_remove_strategy_script_strategy_rendered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='rendered',
        ),
    ]
